MyWebsite/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app_pages.urls')),
    path('blog/', include('app_blog.urls', namespace='blog')),
    path('portfolio/', include('app_portfolio.urls')),
    path('stats/', include('app_stats.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app_pages.urls')),
    path('blog/', include('app_blog.urls', namespace='blog')),
    path('portfolio/', include('app_portfolio.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/app_blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'app_blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

MyWebsite/app_pages/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "app_pages"

urlpatterns = [
    path("", InicioPageView.as_view(), name='inicio'),
    path("sobre-mi/", SobreMiPageView.as_view(), name='sobremi'),
    path("resumen/", ResumenPageView.as_view(), name='resumen'),
    path("contactar/", ContactarPageView.as_view(), name='contactar'),

    path('user_settings/', views.userSettings, name="user_settings"),
    path('update_theme/', views.updateTheme, name="update_theme"),


]

MyWebsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!--
    <meta name="description" content="BreezyCV - Resume / CV / vCard Template" />
    <meta name="keywords" content="vcard, resposnive, retina, resume, jquery, css3, bootstrap, Material CV, portfolio" />
    <meta name="author" content="lmpixels" />-->

    <link rel="shortcut icon" href="favicon.ico">

      <title>{% block titulo %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/reset.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/bootstrap-grid.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/animations.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/perfect-scrollbar.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/mainlight.css' %}"  type="text/css" id="mystylesheet">

    <link rel="stylesheet" href="{% static "css/fonts/fontawesome-free-5.15.3-web/css/all.min.css" %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">


    <script src="{% static "js/modernizr.custom.js" %}"></script>
  </head>

  <body>
    <!-- Animated Background
    <div class="lm-animated-bg" style="background-image: url(img/main_bg.png);"></div>
     /Animated Background -->

    <!-- Loading animation -->
    <div class="preloader">
      <div class="preloader-animation">
        <div class="preloader-spinner">
        </div>
      </div>
    </div>
    <!-- /Loading animation -->

    <div class="page">
      <div class="page-content">

          <header id="site_header" class="header mobile-menu-hide">
            <div class="header-content">
              <div class="header-photo">
                <img src="{% static "img/imgperfil.jpg" %}" alt="Alejandro Planells">

              </div>
              <div class="header-titles">
                <h2>Alejandro Planells</h2>
                <h4>Desarrollador Frontend</h4>
              </div>
            </div>

            <ul class="main-menu">
              <li class="active">
                <a href="{% url "app_pages:inicio" %}" class="nav-anim">
                  <span class="menu-icon lnr lnr-home" {% if inicio == "inicio" %}style="color: #00abff"{% endif %}></span>
                  <span class="link-text">Inicio</span>
                </a>
              </li>
              <li>
                <a href="{% url "app_pages:sobremi" %}" class="nav-anim">
                  <span class="menu-icon lnr lnr-user" {% if sobremi == "sobremi" %}style="color: #00abff"{% endif %}></span>
                  <span class="link-text">Sobre mi</span>
                </a>
              </li>
              <li>
                <a href="{% url "app_pages:resumen" %}" class="nav-anim">
                  <span class="menu-icon lnr lnr-graduation-hat" {% if resumen == "resumen" %}style="color: #00abff"{% endif %}></span>
                  <span class="link-text">Resumen</span>
                </a>
              </li>
              <li>
                <a href="{% url "portfolio" %}" class="nav-anim">
                  <span class="menu-icon lnr lnr-briefcase"></span>
                  <span class="link-text">Portfolio</span>
                </a>
              </li>
              <li>
                <a href="{% url "app_blog:post_list" %}" class="nav-anim">
                  <span class="menu-icon lnr lnr-book"></span>
                  <span class="link-text">Blog</span>
                </a>
              </li>
              <li>
                <a href="{% url "app_pages:contactar" %}" class="nav-anim">
                  <span class="menu-icon lnr lnr-envelope" {% if contactar == "contactar" %}style="color: #00abff"{% endif %}></span>
                  <span class="link-text">Contactar</span>
                </a>
              </li>
            </ul>

            <div class="social-links">
                <ul>
                    <li><a href="https://www.linkedin.com/in/alejandro-planells/" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                    <li><a href="https://www.instagram.com/alex_planells/" target="_blank"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://twitter.com/Pucheritoo2001" target="_blank"><i class="fab fa-twitter"></i></a></li>
                </ul>
            </div>

            <div class="header-buttons">
              <a href="#" target="_blank" class="btn btn-primary">Descargar CV</a>
            </div>




            <div class="copyrights">
                <button class="btn btn-light" onclick="swapStyles('mainlight.css')">Modo Claro</button>
              <button class="btn btn-dark" onclick="swapStyles('maindark.css')">Modo Oscuro</button><br>
                © 2020 Todos los derechos reservador. </div>
          </header>

          <!-- Mobile Navigation -->
          <div class="menu-toggle">
            <span></span>
            <span></span>
            <span></span>
          </div>
          <!-- End Mobile Navigation -->

          <!-- Arrows Nav -->
      <!--
          <div class="lmpixels-arrows-nav">
            <div class="lmpixels-arrow-right"><i class="lnr lnr-chevron-right"></i></div>
            <div class="lmpixels-arrow-left"><i class="lnr lnr-chevron-left"></i></div>
          </div>
      -->
          <!-- End Arrows Nav -->

          <div class="content-area">
            <div class="animated-sections">

            {% block contenedor %}

            {% endblock %}

            </div>
          </div>

      </div>

    </div>

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/modernizr.custom.js" %}"></script>
    <!-- <script src="{% static "js/animating.js" %}"></script> -->

    <script src="{% static "js/imagesloaded.pkgd.min.js" %}"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>

    <script src='{% static "js/perfect-scrollbar.min.js" %}'></script>
    <script src='{% static "js/jquery.shuffle.min.js" %}'></script>
    <script src='{% static "js/masonry.pkgd.min.js" %}'></script>
    <script src='{% static "js/owl.carousel.min.js" %}'></script>
    <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrDf32aQTCVENBhFJbMBKOUTiUAABtC2o"></script>
    <script src="{% static "js/jquery.googlemap.js" %}"></script>
    <script src="{% static "js/validator.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>

  	<script type="text/javascript">

		function getCookie(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');



		var cssFile = "{% static 'css' %}"


		function swapStyles(sheet){
			document.getElementById('mystylesheet').href = cssFile + '/' + sheet
			localStorage.setItem('theme', sheet)

			updateTheme(sheet)
		}


		function loadSettings(){
			//Call data and set local storage

			var url = "{% url 'app_pages:user_settings' %}"
			fetch(url, {
				method:'GET',
				headers:{
					'Content-type':'application/json'
				}
			})
			.then((response) => response.json())
			.then(function(data){

				console.log('Data:', data)

				var theme = data.value;

				if (theme == 'mainlight.css' || null){
					swapStyles('mainlight.css')
				}else if(theme == 'maindark.css'){
					swapStyles('maindark.css')
				}


			})

		}

		loadSettings()


		function updateTheme(theme){
			var url = "{% url 'app_pages:update_theme' %}"
			fetch(url, {
				method:'POST',
				headers:{
					'Content-type':'application/json',
					'X-CSRFToken':csrftoken,
				},
				body:JSON.stringify({'theme':theme})
			})
		}
	</script>


  </body>
</html>