MyWebsite/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app_pages.urls')),
    path('blog/', include('app_blog.urls', namespace='blog')),
    path('portfolio/', include('app_portfolio.urls')),
    path('stats/', include('app_stats.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app_pages.urls')),
    path('blog/', include('app_blog.urls', namespace='blog')),
    path('portfolio/', include('app_portfolio.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/app_blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'app_blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

MyWebsite/app_pages/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "app_pages"

urlpatterns = [
    path("", InicioPageView.as_view(), name='inicio'),
    path("sobre-mi/", SobreMiPageView.as_view(), name='sobremi'),
    path("resumen/", ResumenPageView.as_view(), name='resumen'),
    path("contactar/", ContactarPageView.as_view(), name='contactar'),

    path('user_settings/', views.userSettings, name="user_settings"),
    path('update_theme/', views.updateTheme, name="update_theme"),


]

MyWebsite/templates/blog/detail.html
{% extends "../base.html" %}
{% load static %}
{% load blog_tags %}
<!-- ************************** -->
{% block title %}{{ post.title }}{% endblock %}
{% block contenedor %}

<!-- Blog Subpage -->
            <div class="single-page-content">

              <article class="post">

                <div class="post-thumbnail">
                  <img src="{{ post.foto.url }}" width="100%" alt="image">
                </div>

                <div class="post-content">
                  <!-- /Entry header -->
                  <header class="entry-header">
                    <!-- Entry meta

                    <div class="entry-meta entry-meta-top">
                      <span><a href="{% url "app_pages:inicio" %}" rel="category tag">UI</a></span>
                    </div>
                     /Entry meta -->

                    <h2 class="entry-title">{{ post.title }}</h2>
                  </header>
                  <!-- /Entry header -->

                  <!-- Entry content -->
                  <div class="entry-content">
                    <div class="row">
                      <div class=" col-xs-12 col-sm-12 ">
                        <div class="col-inner">
                            <p>{{ post.body|markdown }}</p>

                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /Entry content -->

                  <div class="entry-meta entry-meta-bottom">
                    <div class="date-author">
                      <span class="entry-date">
                        <a href="#" rel="bookmark">
                          <i class="far fa-clock"></i> <span class="entry-date">{{ post.publish }}</span>
                        </a>
                      </span>
                      <span class="author vcard">
                        <a class="url fn n" href="#" rel="author"> <i class="fas fa-user"></i> {{ post.author }}</a>
                      </span>
                    </div>

                    <!-- Share Buttons -->

                    <div class="entry-share btn-group share-buttons">
                      <a href="https://www.facebook.com/share/?u=https:localhost:8000{{ post.get_absolute_url }}" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;" class="btn" target="_blank" title="Share on Facebook">
                        <i class="fab fa-facebook-f"></i>
                      </a>

                      <a href="https://twitter.com/intent/tweet?text={{ post.title }} https:localhost:8000{{ post.get_absolute_url }}" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;" class="btn" target="_blank" title="Share on Twitter">
                        <i class="fab fa-twitter"></i>
                      </a>

                    </div>
                    <!-- /Share Buttons -->
                  </div>

                  <div class="post-tags">
                    <div class="tags">
                        {% for tag in post.tags.all %}
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}" title="Ver todos los post con el tag > {{ tag.name }} <" rel="tag">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                  </div>
                    <!-- commends -->
                    <div id="comments" class="comments-area">
                        <div class="block-title">
                            {% with comments.count as total_comments %}
                                <h3>
                                    {{ total_comments }} Comentario{{ total_comments|pluralize }}
                                </h3>
                            {% endwith %}
                        </div>
                        <ol class="comment-list">
                            {% for comment in comments %}
                                <li id="comment-7" class="comment even thread-even depth-1">
                                    <article id="div-comment-7" class="comment-body">
                                        <footer class="comment-meta">
                                            <div class="comment-author vcard" style="color: #9e9e9e">
                                                {{ comment.nombre }} <small>| {{ comment.created }}</small>

                                            </div>
                                            {{ comment.body|linebreaks }}
                                        </footer>
                                    </article>
                                </li>
                                <br>
                            {% empty %}
                                <p>Ningun comentario, de momento.</p>
                            {% endfor %}
                        </ol><!-- .comment-list -->

                        <br>

                        <!-- RESPUESTA COMENTARIOS -->
                        <div id="respond" class="comment-respond">
                            {% if new_comment %}
                                <h2>Tu comentario se publicara cuando sea aprobado.</h2>
                            {% else %}
                                <h3 id="reply-title" class="block-title">Dejar un comentario </h3>

                                <form method="post" id="commentform" class="comment-form" novalidate="">
                                    {% csrf_token %}
                                    <div class="form-group form-group-with-icon comment-form-message">
                                        <textarea id="comment" class="form-control" name="{{ comment_form.body.name }}" placeholder="Comentario" cols="45" rows="8" aria-required="true"></textarea>
                                        <div class="form-control-border"></div><i class="form-control-icon fa fa-comment"></i></div>

                                    <div class="form-group form-group-with-icon comment-form-author">
                                        <input id="author" class="form-control" name="{{ comment_form.nombre.name }}" type="text" placeholder="Nombre"size="30" aria-required="true">
                                        <div class="form-control-border"></div><i class="form-control-icon fa fa-user"></i></div>

                                    <div class="form-group form-group-with-icon comment-form-email">
                                        <input id="email" class="form-control" name="{{ comment_form.email.name }}" type="text" placeholder="Email" size="30" aria-required="true" >
                                        <div class="form-control-border"></div><i class="form-control-icon fa fa-envelope"></i></div>

                                    <!-- <p class="comment-form-cookies-consent">
                                        <input id="wp-comment-cookies-consent" name="wp-comment-cookies-consent" type="checkbox" value="yes" >
                                        <label for="wp-comment-cookies-consent">Save my name, email, and website in this browser for the next time I comment.</label>
                                    </p> -->

                                    <p class="form-submit">
                                        <input name="submit" type="submit" id="submit" class="submit" value="Añadir comentario">
                                    </p>

                                    <input type="hidden" id="ak_js" name="ak_js" value="238">
                                    <textarea name="ak_hp_textarea" cols="45" rows="8" maxlength="100" style="display: none !important;"></textarea>
                                </form>
                            {% endif %}
                    </div><!-- #respond -->
                </div><!-- end commends -->
                </div>
              </article>
            </div>

<!-- End of Blog Subpage -->
{% endblock %}

MyWebsite/templates/blog/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

MyWebsite/templates/blog/list.html
{% extends "../base.html" %}
{% load blog_tags %}

<!-- ************************** -->
{% block titulo %}Blog{% endblock %}
{% block contenedor %}

<!-- Blog Subpage -->
<section class="animated-section start-page ps section-active ps--theme_default">
<div class="page-title">
  <h2>Blog</h2>
</div>

    {% if tag %}
        <h2>Post con el tag: "{{ tag.name }}"</h2> <br>
    {% endif %}



<div class="section-content">
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <div class="blog-masonry two-columns clearfix">


        <!-- Blog Post -->
          {% for post in posts %}

        <div class="item post-1">
          <div class="blog-card">
            <div class="media-block">


                  {% for tag in post.tags.all %}
                      {% if forloop.first %}
                        <div class="category">
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}" title="Ver todos los post con el tag {{ tag.name }}">{{ tag.name }}</a>
                        </div>
                      {% endif %}
                  {% endfor %}

              <a href="{{ post.get_absolute_url }}">
                <img src="{{ post.foto.url }}" class="size-blog-masonry-image-two-c" alt="{{ post.title }}" title="" />
                <div class="mask"></div>
              </a>
            </div>
            <div class="post-info">
              <div class="post-date">Publicado {{ post.publish }} por {{ post.author }}</div>
              <a href="{{ post.get_absolute_url }}">
                <h4 class="blog-item-title">{{ post.title }}</h4>
              </a>
            </div>
          </div>
        </div>

          {% endfor %}
        <!-- End of Blog Post 1 -->



      </div>
    </div>

        <!-- Paginacion -->
          <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
          </span>
        </div>
        <!-- End of Paginacion -->

  </div>
</div>

</section>
<!-- End of Blog Subpage -->
{% endblock %}

MyWebsite/templates/blog/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

MyWebsite/templates/blog/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

MyWebsite/templates/blog/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}